List models = [
  "Param",
  "Param Wooden",
  "Anchor Ziva White",
  "Anchor Ziva Black",
  "Anchor Penta White",
  "Anchor Penta White Gina",
  "Anchor Penta Black",
  "Anchor Penta White Flat",
  "Anchor Penta Black Flat",
  "Greatwhite",
  "L&T Engem",
  "Havells Fabio",
  "Anchor Roma Classic",
  "Anchor Roma Urban",
];

List modelsCode = [
  "param",
  "paramWooden",
  "anchorZivaWhite",
  "anchorZivaBlack",
  "",
  "anchorPentaWhiteGina",
  "anchorPentaBlack",
  "anchorPentaWhiteFlat",
  "anchorPentaBlackFlat",
  "greatwhite",
  "l&TEngem",
  "havellsFabio",
  "anchorRomaClassic",
  "anchorRomaUrban",
];

List Navigate = [
  "/paramSetup",
  "/paramWoodenSetup",
  "/zivaWhiteSetup",
  "/zivaBlackSetup",
  "/pentaWhSetup",
  "/pentaWhiteGinaSetup",
  "/pentaBlackSetup",
  "/pentaWhiteFlatSetup",
  "/pentaBlackFlatSetup",
  "/greatWhiteSetup",
  "/l&tSetup",
  "/hevellsFabioSetup",
  "/romaClassicSetup",
  "/romaUrbanSetup",
];

List modelImages = [
  "assets/images/pentaModular.jpg",
  "assets/images/pentaModular.jpg",
  "assets/images/pentaModular.jpg",
  "assets/images/pentaModular.jpg",
  "assets/images/pentaModular.jpg",
  "assets/images/pentaModular.jpg",
  "assets/images/pentaModular.jpg",
  "assets/images/pentaModular.jpg",
  "assets/images/pentaModular.jpg",
  "assets/images/pentaModular.jpg",
  "assets/images/pentaModular.jpg",
  "assets/images/pentaModular.jpg",
  "assets/images/pentaModular.jpg",
  "assets/images/pentaModular.jpg",
];

List modelPrefs = [
  "Param",
  "Param_Wooden",
  "Anchor_Ziva_White",
  "Anchor_Ziva_Black",
  "Anchor_Penta_White",
  "Anchor_Penta_White_Gina",
  "Anchor_Penta_Black",
  "Anchor_Penta_White_Flat",
  "Anchor_Penta_Black_Flat",
  "Greatwhite",
  "L&T_Engem",
  "Havells_Fabio",
  "Anchor_Roma_Classic",
  "Anchor_Roma_Urban",
];
